# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxBook_ExampleCodes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RxBook_ExampleCodes
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  target 'RxBook_ExampleCodesTests' do
    inherit! :search_paths
    # Pods for testing
  
  end

  target 'RxBook_ExampleCodesUITests' do
    # Pods for testing
  end

end
